---
service: tidewidget-server
app: app
tenant: ivanoats

plugins:
  - serverless-plugin-webpack
  - serverless-offline
  - serverless-finch
  - serverless-domain-manager

custom:
  client:
    bucketName: westpointwind
    distributionFolder: client/dist
  customDomain:
    domainName: api.westpointwind.com
    basePath: ''
    stage: ${self:provider.stage}
    certificateName: '*.westpointwind.com'
    createRoute53Record: true
    endpointType: regional

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors:
      - enabled: true
        origin: "*"
        # - 'http://127.0.0.1:3000'
        # - 'http://localhost:3000'
        # - 'http://0.0.0.0:3000'
        # - 'http://ipad.ivanstorck.com:3000'
        methods: "GET, PUT, POST"
