service: tidewidget-server

plugins:
  - serverless-plugin-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  # region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors:
      - enabled: true
        origin: "*"
        # - 'http://127.0.0.1:3000'
        # - 'http://localhost:3000'
        # - 'http://0.0.0.0:3000'
        # - 'http://ipad.ivanstorck.com:3000'
        methods: "GET, PUT, POST"