---
service: tidewidget-server
app: westpointwind
org: ivanoats

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-finch
  - serverless-domain-manager

custom:
  client:
    bucketName: westpointwind
    distributionFolder: client/dist
  customDomain:
    domainName: api.westpointwind.com
    basePath: ""
    # stage: provider.stage
    certificateName: "*.westpointwind.com"
    createRoute53Record: true
    apiType: rest
    endpointType: regional

provider:
  apiGateway:
    shouldStartNameWithService: true
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: wpow1
          cors: true
          method: get
